# Generated by Django 5.1.6 on 2025-03-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/avatars/default.jpg', null=True, upload_to='images/avatars/'),
        ),
    ]
