# Generated by Django 5.1.6 on 2025-03-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
        ('users', '0005_profile_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='twitch_link',
            new_name='website',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_ideas',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='ideas.idea'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('idea_owner', 'Idea Owner'), ('business', 'Business / Investor')], default='idea_owner', max_length=20),
        ),
    ]
