# Generated by Django 5.1.6 on 2025-03-19 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0003_alter_notification_recipient_companyprofile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
