# Generated by Django 5.1.6 on 2025-03-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0004_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershiprequest',
            name='company_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnershiprequest',
            name='percentage_share',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
